DarkRPUI = DarkRPUI or {}; DarkRPUI.UI = DarkRPUI.UI or {}
local UI = DarkRPUI.UI
local blurMat
function UI.RoundedBox(r,x,y,w,h,c) draw.RoundedBox(r or DarkRPUI.ThemeRadius(),x,y,w,h,c or DarkRPUI.Color("panel")) end
function UI.OutlinedBox(r,x,y,w,h,c,border) UI.RoundedBox(r,x,y,w,h,c); surface.SetDrawColor(border or DarkRPUI.Color("border")); surface.DrawOutlinedRect(x,y,w,h,1) end
function UI.Text(t,f,x,y,c,ax,ay) draw.SimpleText(t or "", f or "DarkRPUI.Body", x,y,c or DarkRPUI.Color("text"), ax or TEXT_ALIGN_LEFT, ay or TEXT_ALIGN_TOP) end
function UI.DrawBlur(panel, amount) if DarkRPUI.Settings and DarkRPUI.Settings.blur == false then return end if not DarkRPUI.Config.BlurEnabled then return end blurMat = blurMat or Material("pp/blurscreen") local x,y=panel:LocalToScreen(0,0); surface.SetDrawColor(255,255,255); surface.SetMaterial(blurMat); for i=1,3 do blurMat:SetFloat("$blur", (i/3)*(amount or 6)); blurMat:Recompute(); render.UpdateScreenEffectTexture(); surface.DrawTexturedRect(-x,-y,ScrW(),ScrH()) end end
function UI.StyleButton(btn, accent) btn:SetTextColor(DarkRPUI.Color("text")); btn:SetFont("DarkRPUI.Body"); btn.Paint=function(s,w,h) UI.OutlinedBox(10,0,0,w,h, s:IsHovered() and (accent or DarkRPUI.Color("cardHover")) or DarkRPUI.Color("card"), s:IsHovered() and DarkRPUI.Color("accent") or DarkRPUI.Color("border")) end end
function UI.MakeHeader(parent, title, subtitle) local p=vgui.Create("DPanel",parent); p:SetTall(DarkRPUI.Util.Scale(72)); p.Paint=function(_,w,h) UI.Text(title,"DarkRPUI.Title",0,4); UI.Text(subtitle,"DarkRPUI.Small",2,42,DarkRPUI.Color("subtext")) end; return p end
function UI.MakeCard(parent, title, body, action, footer) local c=vgui.Create("DButton",parent); c:SetText(""); c.Title=title; c.Body=body; c.Footer=footer; c.DoClick=action or function() end; c.Paint=function(s,w,h) UI.OutlinedBox(12,0,0,w,h,s:IsHovered() and DarkRPUI.Color("cardHover") or DarkRPUI.Color("card"),s:IsHovered() and DarkRPUI.Color("accent") or DarkRPUI.Color("border")); UI.Text(s.Title,"DarkRPUI.Subtitle",16,14); draw.DrawText(s.Body or "","DarkRPUI.Small",16,42,DarkRPUI.Color("subtext"),TEXT_ALIGN_LEFT); if s.Footer then UI.Text(s.Footer,"DarkRPUI.Tiny",w-14,h-22,DarkRPUI.Color("accent"),TEXT_ALIGN_RIGHT) end end; return c end
function UI.Badge(x,y,text,color) surface.SetFont("DarkRPUI.Tiny"); local tw=surface.GetTextSize(text); UI.RoundedBox(6,x,y,tw+14,20,color or DarkRPUI.Color("accent")); UI.Text(text,"DarkRPUI.Tiny",x+7,y+4,color_white) return tw+14 end
