DarkRPUI = DarkRPUI or {}; DarkRPUI.Settings = DarkRPUI.Settings or {}; DarkRPUI.Config = DarkRPUI.Config or {}; DarkRPUI.UI = DarkRPUI.UI or {}
local UI = DarkRPUI.UI
local selectedCategory = "theme"
local categories = {
    {id="theme", icon="◆", name="Theme", desc="Preset and accent"}, {id="hud", icon="▣", name="HUD", desc="Layout and visibility"},
    {id="f4", icon="◈", name="F4", desc="Menus and cards"}, {id="notifications", icon="◍", name="Notifications", desc="Toasts and sounds"},
    {id="performance", icon="⌁", name="Performance", desc="Blur and animation"}, {id="accessibility", icon="✦", name="Accessibility", desc="Motion and font scale"}, {id="admin", icon="⚑", name="Admin", desc="Staff defaults", staffOnly=true}
}
local accents={Color(74,142,255),Color(166,107,255),Color(235,64,82),Color(48,220,151),Color(245,190,80),Color(55,118,245)}
local function save(toast) DarkRPUI.Config.AnimationSpeed=(DarkRPUI.Settings.reduce_motion and 0.04 or 0.16)*(DarkRPUI.Settings.animation_speed or 1); if DarkRPUI.SaveSettings then DarkRPUI.SaveSettings() end; if DarkRPUI.SyncSettings then DarkRPUI.SyncSettings() end; if toast and DarkRPUI.Notify then DarkRPUI.Notify("success","Settings saved","Your premium UI preferences were updated.") end end
local function card(parent,title,desc,h) local p=vgui.Create("DPanel",parent); p:Dock(TOP); p:DockMargin(0,0,0,14); p:SetTall(h or 84); p.Hover=0; p.Paint=function(s,w,hh) s.Hover=UI.HoverLerp(s,12); UI.ShadowedBox(16,0,0,w,hh,UI.LerpColor(s.Hover,DarkRPUI.Color("card"),DarkRPUI.Color("cardHover")),UI.LerpColor(s.Hover,DarkRPUI.Color("border"),DarkRPUI.Color("accent")),72); surface.SetDrawColor(DarkRPUI.Color("accent")); surface.DrawRect(0,12,4,hh-24); UI.Text(title,"DarkRPUI.Subtitle",18,14); UI.Text(desc or "","DarkRPUI.Small",18,43,DarkRPUI.Color("subtext")) end; return p end
local function toggle(parent,title,desc,key) local c=card(parent,title,desc,78); local t=UI.PremiumToggle(c,DarkRPUI.Settings[key] ~= false,function(v) DarkRPUI.Settings[key]=v; save(true) end); t:SetSize(74,34); c.PerformLayout=function() t:SetPos(c:GetWide()-94,22) end end
local function slider(parent,title,desc,key,min,max,dec) local c=card(parent,title,desc,98); local s=vgui.Create("DNumSlider",c); s:SetPos(18,58); s:SetSize(c:GetWide()-36,30); s:SetText(""); s:SetMin(min); s:SetMax(max); s:SetDecimals(dec or 2); s:SetValue(DarkRPUI.Settings[key] or 1); c.PerformLayout=function() s:SetWide(c:GetWide()-36) end; UI.StyleTextEntry(s.TextArea); s.OnValueChanged=function(_,v) DarkRPUI.Settings[key]=v; save(false) end end
local function combo(parent,title,desc,key,values) local c=card(parent,title,desc,92); local b=UI.PremiumComboBox(c); b:SetSize(250,40); b:SetValue(DarkRPUI.Settings[key] or values[1]); for _,v in ipairs(values) do b:AddChoice(v,v) end; c.PerformLayout=function() b:SetPos(c:GetWide()-270,26) end; b.OnSelect=function(_,_,_,id) DarkRPUI.Settings[key]=id; save(true) end end
local function previews(parent) local c=card(parent,"Live previews","HUD, notification, button, and card styling update with the active theme.",220); c.PaintOver=function(_,w,h) UI.ShadowedBox(16,18,70,330,118,DarkRPUI.Color("panel"),DarkRPUI.Color("border"),70); UI.Text("Preview Citizen","DarkRPUI.Subtitle",38,88); UI.Text("Civil Protection • "..DarkRPUI.Util.FormatMoney(42000),"DarkRPUI.Small",38,114,DarkRPUI.Color("subtext")); UI.RoundedBox(5,38,148,130,8,DarkRPUI.Color("success")); UI.RoundedBox(5,184,148,110,8,DarkRPUI.Color("accent")); UI.ShadowedBox(14,370,76,w-390,74,DarkRPUI.Color("card"),DarkRPUI.Color("accent"),60); UI.Text("✓ Notification","DarkRPUI.Subtitle",392,90,DarkRPUI.Color("success")); UI.Text("Premium toast preview with progress.","DarkRPUI.Small",392,118,DarkRPUI.Color("subtext")); UI.RoundedBox(4,392,136,180,4,DarkRPUI.Color("success")); UI.ShadowedBox(12,370,164,180,38,DarkRPUI.Color("accent"),DarkRPUI.Color("border"),45); UI.Text("Premium Button","DarkRPUI.Body",460,173,DarkRPUI.Color("text"),TEXT_ALIGN_CENTER) end end
local function themes(parent)
    local c=card(parent,"Theme preset","Obsidian Blue, Midnight Purple, Carbon Red, Emerald City, Gold Luxury, Clean Light, or Custom Accent.",170)
    local x=18
    for id,t in SortedPairs(DarkRPUI.Themes or {}) do
        local b=vgui.Create("DButton",c); b:SetText(""); b:SetPos(x,72); b:SetSize(150,74)
        b.Paint=function(_,w,h)
            UI.ShadowedBox(14,0,0,w,h,t.colors.panel,t.colors.border,50)
            UI.RoundedBox(8,12,12,44,16,t.colors.accent); UI.RoundedBox(8,12,36,88,10,t.colors.card)
            UI.Text(t.name,"DarkRPUI.Tiny",12,56,t.colors.text)
            if (DarkRPUI.Settings.theme or DarkRPUI.ActiveTheme)==id then UI.Badge(w-50,10,"ON",t.colors.success) end
        end
        b.DoClick=function() DarkRPUI.Settings.theme=id; if DarkRPUI.SetTheme then DarkRPUI.SetTheme(id) end; save(true) end
        x=x+162
    end
    local a=card(parent,"Accent color","Used by Custom Accent and shared glow states.",116)
    for i,col in ipairs(accents) do
        local b=vgui.Create("DButton",a); b:SetText(""); b:SetPos(18+(i-1)*58,62); b:SetSize(44,36)
        b.Paint=function(_,w,h) UI.ShadowedBox(12,0,0,w,h,col,DarkRPUI.Color("border"),45) end
        b.DoClick=function() DarkRPUI.Settings.accent={col.r,col.g,col.b}; DarkRPUI.Settings.theme="custom_accent"; DarkRPUI.SetTheme("custom_accent"); save(true) end
    end
end

function DarkRPUI.SettingsPanel(parent)
    local p=vgui.Create("DPanel",parent); p:Dock(FILL); p:DockMargin(20,0,20,20); p.Paint=function() end
    local left=UI.PremiumPanel(p); left:Dock(LEFT); left:SetWide(244); left:DockMargin(0,0,18,0); left.Paint=function(_,w,h) UI.ShadowedBox(18,0,0,w,h,DarkRPUI.Color("panel"),DarkRPUI.Color("border"),105); UI.Text("Settings","DarkRPUI.Title",20,18); UI.Text("Premium control center","DarkRPUI.Small",22,54,DarkRPUI.Color("subtext")) end
    local right=vgui.Create("DScrollPanel",p); right:Dock(FILL); UI.StyleScrollbar(right)
    local function rebuild() right:Clear(); if selectedCategory=="theme" then themes(right); previews(right) elseif selectedCategory=="hud" then combo(right,"HUD style","Choose the dashboard HUD layout.","hud_style",{"Compact Corner","Modern Bar","Center Minimal"}); combo(right,"HUD position","Anchor the main HUD.","hud_position",{"bottom-left","bottom-right","top-left","top-right"}); slider(right,"HUD scale","Fine tune HUD card sizing.","hud_scale",0.75,1.35,2); for _,v in ipairs({{"compact","Compact mode"},{"show_money","Show money"},{"show_salary","Show salary"},{"show_hunger","Show hunger"},{"show_level","Show level"},{"show_ammo","Show ammo"},{"show_laws","Show laws"},{"show_agenda","Show agenda"},{"blur","Blur on/off"}}) do toggle(right,v[2],"Client-side saved HUD preference.",v[1]) end; previews(right) elseif selectedCategory=="f4" then slider(right,"Animation speed","Controls F4 transitions and hover response.","animation_speed",0.5,1.75,2); toggle(right,"Favorite jobs","Save star selections locally.","favorites_enabled"); previews(right) elseif selectedCategory=="notifications" then combo(right,"Notification position","Where toast stacks appear.","notification_position",{"top-right","top-left","bottom-right","bottom-left"}); toggle(right,"Notification sounds","Play polished toast sounds.","sounds"); toggle(right,"Notifications enabled","Use safe DarkRP notification override.","notifications"); previews(right) elseif selectedCategory=="performance" then slider(right,"Blur strength","Visual glass intensity setting.","blur_strength",0,12,0); slider(right,"Animation speed","Global animation multiplier.","animation_speed",0.5,1.75,2); toggle(right,"Reduce motion","Shortens animations for performance/accessibility.","reduce_motion") elseif selectedCategory=="accessibility" then slider(right,"Font scale","Reserved scaling preference for servers with custom fonts.","font_scale",0.85,1.25,2); toggle(right,"Reduce motion","Minimize slide and fade duration.","reduce_motion") elseif selectedCategory=="admin" then card(right,"Admin backend","Server-authoritative moderation actions with permission checks, rank protection, and integration hooks.",110); previews(right) end; local reset=UI.PremiumButton(right,"Reset defaults",function() UI.Confirm("Reset settings","Restore the premium UI defaults?","Reset","Cancel",function(ok) if ok then DarkRPUI.Settings={theme="obsidian_blue",hud=true,hud_scale=1,hud_position="bottom-left",hud_style="Modern Bar",blur=true,notifications=true,notification_position="top-right",sounds=true,compact=false,show_money=true,show_salary=true,show_hunger=true,show_level=true,show_ammo=true,show_laws=true,show_agenda=true,animation_speed=1,reduce_motion=false,font_scale=1,favorites={}}; DarkRPUI.SetTheme("obsidian_blue"); save(true); rebuild() end end) end,DarkRPUI.Color("error")); reset:Dock(TOP); reset:DockMargin(0,4,0,0); reset:SetTall(46) end
    local y=92; for _,cat in ipairs(categories) do if not cat.staffOnly or DarkRPUI.Util.IsAdmin(LocalPlayer()) then local b=UI.PremiumIconButton(left,cat.icon.."  "..cat.name,function() selectedCategory=cat.id; rebuild() end); b:SetPos(14,y); b:SetSize(216,58); b.ActiveFunc=function() return selectedCategory==cat.id end; y=y+68 end end; rebuild()
end
concommand.Add("darkrpui_settings", function() if DarkRPUI.F4 and DarkRPUI.F4.Open then DarkRPUI.F4.Open() end end)
