DarkRPUI = DarkRPUI or {}; DarkRPUI.Settings = DarkRPUI.Settings or {}; DarkRPUI.Config = DarkRPUI.Config or {}; DarkRPUI.UI = DarkRPUI.UI or {}
function DarkRPUI.SettingsPanel(parent)
    local p=vgui.Create("DPanel",parent); p:Dock(FILL); p:DockMargin(20,0,20,20); p.Paint=function() end
    local y=10
    local function save() if DarkRPUI.SaveSettings then DarkRPUI.SaveSettings() end; if DarkRPUI.SyncSettings then DarkRPUI.SyncSettings() end end
    local function toggle(label,key,tip) local b=DarkRPUI.UI.MakeAnimatedCard(p,label,""); b:SetPos(0,y); b:SetSize(360,46); b:SetText(""); DarkRPUI.UI.AttachTooltip(b,tip); b.PaintOver=function(_,w,h) DarkRPUI.UI.Text(label,"DarkRPUI.Body",16,13); DarkRPUI.UI.Badge(w-70,13,DarkRPUI.Settings[key] and "ON" or "OFF",DarkRPUI.Settings[key] and DarkRPUI.Color("success") or DarkRPUI.Color("error")) end; b.DoClick=function() DarkRPUI.UI.PlayClick(); DarkRPUI.Settings[key]=not DarkRPUI.Settings[key]; save() end; y=y+56 end
    toggle("Premium HUD", "hud", "Enable the custom premium HUD."); toggle("Blur", "blur", "Toggle background blur on menus."); toggle("Notification sounds", "sounds", "Play sounds for clicks and notifications."); toggle("Compact mode", "compact", "Use tighter HUD and notification layouts.")
    local scaleCard=vgui.Create("DPanel",p); scaleCard:SetPos(0,y); scaleCard:SetSize(460,58); scaleCard.Paint=function(_,w,h) DarkRPUI.UI.ShadowedBox(14,0,0,w,h,DarkRPUI.Color("card"),DarkRPUI.Color("border"),60) end
    local scale=vgui.Create("DNumSlider",scaleCard); scale:Dock(FILL); scale:DockMargin(14,4,14,4); scale:SetText("HUD scale"); scale:SetMin(0.75); scale:SetMax(1.35); scale:SetDecimals(2); scale:SetValue(DarkRPUI.Settings.hud_scale or 1); scale.OnValueChanged=function(_,v) DarkRPUI.Settings.hud_scale=v; save() end; y=y+70
    local pos=vgui.Create("DComboBox",p); pos:SetPos(0,y); pos:SetSize(320,42); pos:SetValue(DarkRPUI.Settings.notification_position or "top-right"); for _,v in ipairs({"top-right","top-left","bottom-right","bottom-left"}) do pos:AddChoice(v,v) end; DarkRPUI.UI.StyleCombo(pos); pos.OnSelect=function(_,_,_,id) DarkRPUI.Settings.notification_position=id; save() end; y=y+54
    local theme=vgui.Create("DComboBox",p); theme:SetPos(0,y); theme:SetSize(320,42); theme:SetValue(DarkRPUI.Theme(DarkRPUI.ActiveTheme).name); for id,t in pairs(DarkRPUI.Themes or {}) do theme:AddChoice(t.name,id) end; DarkRPUI.UI.StyleCombo(theme); theme.OnSelect=function(_,_,_,id) DarkRPUI.Settings.theme=id; if DarkRPUI.SetTheme then DarkRPUI.SetTheme(id) end; save() end
end
concommand.Add("darkrpui_settings", function() if DarkRPUI.F4 and DarkRPUI.F4.Open then DarkRPUI.F4.Open() end end)
